config:
  default: true
  MD004:
    style: asterisk
  MD013: false
  MD026:
    punctuation: '.,;:'
  MD029:
    style: ordered
  MD033: false
  MD034: false
  MD041: false
  MD046: false # Allow indented code blocks (which are output by nbconvert)
  MD051: false
ignores:
  - CHANGELOG.md
  - docs/CHANGELOG.md
  - "{,docs/}{RELEASE,release}.md"
  - tools/autotag/templates/**/*.md
